### ISSUE TITLE
error creating chia daemon

### ISSUE THREAD

**Issue by gurkburk76** [Eelviny/chia-docker#1] opened 2021-05-05 19:28 UTC
I get this when i start the farmer, now i do understand that there are/will be error before the first plot is created but what concerns me is that i'm asked to port forward a port, why is that?

Do i *need* to run a full node and sortof let other connect to it via port 8444? I assume a wallet is created for my since i got my address and mnemonics.

error regarding network:
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up
Connection error. Check if wallet is running at 9256

errors when starting farmer:
Added plot directory "/plots".
Daemon not started yet
Starting daemon
Traceback (most recent call last):
File "/usr/local/bin/chia", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/chia/cmds/chia.py", line 77, in main
cli()  # pylint: disable=no-value-for-parameter
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/chia/cmds/chia.py", line 60, in run_daemon_cmd
asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/chia/daemon/server.py", line 946, in async_run_daemon
await ws_server.start()
File "/usr/local/lib/python3.7/site-packages/chia/daemon/server.py", line 145, in start
ssl=self.ssl_context,
File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 965, in __await_impl__
server = await self._create_server()
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
% (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon

I guess  few of these might go away when i create a plot in a few hours, i guess it will also be easier to farm when pools get created.

**Comment by Eelviny** [comment] 2021-05-06 07:10
Hey! Looks like there's something up with the networking configuration of your Docker setup. What Operating System are you using?

Regarding port 8444 - it may work without it, but you will experience frequent sync issues if you don't. If you're out of sync, you won't receive any challenges and therefore won't earn any chia. As Chia is a decentralised network like other cryptos and Bittorrent, it relies on people connecting to you as well as you connecting to other people. https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

**Comment by gurkburk76** [comment] 2021-05-06 08:13
PRETTY_NAME="Ubuntu 18.04.5 LTS"
I'm running a few other containers without issues, Docker version 20.10.6, build 370c289
Only other ports i have used up in docker is 8443 for another container, and 9000.

network config of container looks.. fine i guess.
 "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b6645afd4dc830e44847948975eff1e78df14aa57295b61c8b363b21eb203f58",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8444"
                    }
                ]
            },
            "SandboxKey": "/run/snap.docker/netns/b6645afd4dc8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "5e1baf20798554d79a80fdd7e0d909b2c1573acabecdb3fd1ca36dd4f1eb4c3a",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "*REDACTED*",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d34881e0a6ae96995b7cbc7dda1a882245d936b968e7230b33210d2f409055dd",
                    "EndpointID": "5e1baf20798554d79a80fdd7e0d909b2c1573acabecdb3fd1ca36dd4f1eb4c3a",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "*REDACTED*",
                    "DriverOpts": null
                }
            }
        }
    }

How else can i help to troubleshoot it ?

**Comment by gurkburk76** [comment] 2021-05-06 08:29
tried disabling ipv6 in a few ways, didn't work. i though the "OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address" could have something to do with it, i guess not.

**Comment by gurkburk76** [comment] 2021-05-06 09:07
This seems to be the solution, the sed part.
https://github.com/Chia-Network/chia-blockchain/issues/2265

Are you able to do changes to the image?

**Comment by Eelviny** [comment] 2021-05-06 09:47
I added the workaround! Let me know if the issue is solved.

**Closed as completed** 2021-05-06 09:47 UTC
Labels: bug
